# Generated by Django 5.0 on 2024-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0002_outputtable_delete_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, null=True)),
                ('authors', models.TextField(null=True)),
                ('alt', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OutputTable',
        ),
    ]
