# Generated by Django 5.0 on 2024-03-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0005_output_delete_outputtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
